# Generated by Django 5.0.3 on 2024-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_user_name', models.CharField(max_length=150, unique=True)),
                ('m_password', models.CharField(max_length=128)),
            ],
        ),
    ]
